### ISSUE TITLE
Problem when construct two GeolocationSensor.read() with async/await

### ISSUE THREAD

**Issue by Honry** [kenchris/sensor-polyfills#10]
```
async function test() {
  const geo1 = await GeolocationSensor.read(); 
  console.log(geo1); 
  const geo2 = await GeolocationSensor.read();
  console.log(geo2);
}
test();
```

when execute above code, only `geo1` returns the value.

**Comment by kenchris** [comment]
It seems to only trigger if the position changes (you can test that with devtools)

**Comment by kenchris** [comment]
![screenshot from 2018-02-28 15-13-09](https://user-images.githubusercontent.com/1101339/36792131-ea38d968-1c99-11e8-81e2-bb03f72c736a.png)

**Comment by kenchris** [comment]
This basically brings us to how we handle old values... 

In the code we actually set max age to 0, but apparently that doesn't trigger a new update to watchPosition even if the position is fixed in DevTools. This is probably a Chrome bug, so if you could verify that and submit a bug to crbug.com/new that would be great

**Comment by kenchris** [comment]
Nope, it actually seems to work - but it comes up with the permission dialog every time

![screenshot from 2018-02-28 15-30-01](https://user-images.githubusercontent.com/1101339/36792938-44c2b9f6-1c9c-11e8-878c-7714ec6bf800.png)

**Comment by kenchris** [comment]
OK, I found the error! The watchId was a promise and not the value :-) unwatching a promise really messed the geolocation API up
